### ISSUE TITLE
Make the homepage hero display a message when no open listings are available

### ISSUE THREAD

**Issue by callaghanc** [Exygy/bloom#46]
<img width="1071" alt="Screen Shot 2019-09-10 at 1 33 05 PM" src="https://user-images.githubusercontent.com/1117776/64648343-8edc3d00-d3cf-11e9-9c11-ce66e04a83bf.png">

**Comment by software-project** [comment]
I think for this one we need to introduce some kind of store/ actions. I don't know if there was already a discussion about it?

**Comment by bk3c** [comment]
I think the goal was to avoid a store implementation until the next major phase of work, when we do the application form, so that we can consider the state management solution in the context of the form solution. Given that it's super unlikely for the state to switch during a user session, can we not just pass props?

**Comment by software-project** [comment]
Sure, we can use props, but in that case we need to load listings on home page and then when we get to listings. I was trying to avoid it. I can do it that way.

**Comment by bk3c** [comment]
Totally good point. I don't think it's a big deal for the time being (especially since the static listings load should be super-fast), but I agree that it's not ideal longer term.
